version: '4'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "/tmp/postgres/socket:/var/run/postgresql"
 
  psql:
    image: postgres:15.2
    environment:
      - POSTGRES_PASSWORD=pass1234
      - POSTGRES_USER=codeany
      - POSTGRES_DB=mydb
    network_mode: service:app
    volumes:
      - "/tmp/postgres/socket:/var/run/postgresql"